import { create } from 'zustand';
import { persist } from 'zustand/middleware';

const useOnboardingStore = create(
  persist(
    (set) => ({
      step: 1,
      formData: {
        // Step 1: Identity & Biometrics
        firstName: '',
        lastName: '',
        age: '',
        gender: '',
        height: '',
        weight: '',
        bmi: null,
        bmiCategory: '',

        // Step 2: Lifestyle
        activityLevel: '',
        sleepHours: '',
        stressLevel: '',
        isSmoker: false,
        alcoholConsumption: '',

        // Step 3: Diet
        dietType: '',
        sugarIntake: '',
        saltIntake: '',
        eatsLeafyGreens: false,
        eatsFruits: false,
        junkFoodFrequency: '',

        // Step 4: Medical
        allergies: [],
        medicalHistory: [],
        otherConditions: '',

        // Expanded Screening Fields
        weightChangeUnexplained: false,
        fatiguePersistent: false,
        drySkinHairLoss: false,
        coldIntolerance: false,
        familyHistoryThyroid: false,
        autoimmuneHistory: false,
        menstrualCycleIrregular: false,
        facialBodyHairExcess: false,
        persistentAcne: false,
        tryingToConceiveDifficulty: false,
        pcosDiagnosis: false,
        wheezing: false,
        persistentCough: false,
        shortnessBreath: false,
        highPollutionArea: false,
        biomassFuelUse: false,
        seasonalAllergies: false,
        mentalHealthDepressed: false,
        mentalHealthAnxiety: false,
        energyLevelsLow: false,
        lostInterestActivities: false,
        swellingAnkles: false,
        frequentUrination: false,
        foamyUrine: false,
        nsaidOveruse: false,
        liverPain: false,
        fattyLiverDiagnosis: false,
        alcoholFrequency: '',
        familyHistoryDiabetes: false,
        gestationalDiabetesHistory: false,
        frequentThirst: false,
        blurredVision: false,
        slowHealingWounds: false,
        tinglingExtremities: false,
        familyHistoryHypertension: false,
        chestPainActivity: false,
        frequentSevereHeadaches: false,
        nosebleedsHistory: false,
        weeklyExerciseDays: '',
        paleSkinObservation: false,
        brittleNails: false,
        dizzinessOnStanding: false,
        heavyMenstrualFlow: false,
        vegetarianVeganDiet: false,
        recentBloodDonation: false,
      },

      setStep: (step) => set({ step }),
      
      updateFormData: (newData) => 
        set((state) => ({
          formData: { ...state.formData, ...newData }
        })),

      resetOnboarding: () => set({ 
        step: 1, 
        formData: {
          firstName: '',
          lastName: '',
          age: '',
          gender: '',
          height: '',
          weight: '',
          bmi: null,
          bmiCategory: '',
          activityLevel: '',
          sleepHours: '',
          stressLevel: '',
          isSmoker: false,
          alcoholConsumption: '',
          dietType: '',
          sugarIntake: '',
          saltIntake: '',
          eatsLeafyGreens: false,
          eatsFruits: false,
          junkFoodFrequency: '',
          allergies: [],
          medicalHistory: [],
          otherConditions: '',
          weightChangeUnexplained: false,
          fatiguePersistent: false,
          drySkinHairLoss: false,
          coldIntolerance: false,
          familyHistoryThyroid: false,
          autoimmuneHistory: false,
          menstrualCycleIrregular: false,
          facialBodyHairExcess: false,
          persistentAcne: false,
          tryingToConceiveDifficulty: false,
          pcosDiagnosis: false,
          wheezing: false,
          persistentCough: false,
          shortnessBreath: false,
          highPollutionArea: false,
          biomassFuelUse: false,
          seasonalAllergies: false,
          mentalHealthDepressed: false,
          mentalHealthAnxiety: false,
          energyLevelsLow: false,
          lostInterestActivities: false,
          swellingAnkles: false,
          frequentUrination: false,
          foamyUrine: false,
          nsaidOveruse: false,
          liverPain: false,
          fattyLiverDiagnosis: false,
          alcoholFrequency: '',
          familyHistoryDiabetes: false,
          gestationalDiabetesHistory: false,
          frequentThirst: false,
          blurredVision: false,
          slowHealingWounds: false,
          tinglingExtremities: false,
          familyHistoryHypertension: false,
          chestPainActivity: false,
          frequentSevereHeadaches: false,
          nosebleedsHistory: false,
          weeklyExerciseDays: '',
          paleSkinObservation: false,
          brittleNails: false,
          dizzinessOnStanding: false,
          heavyMenstrualFlow: false,
          vegetarianVeganDiet: false,
          recentBloodDonation: false,
        }
      }),
    }),
    {
      name: 'vaidyasetu-onboarding-storage', // name of the item in storage (must be unique)
    }
  )
);

export default useOnboardingStore;
