import React, { useEffect, useState } from 'react';
import { useUser } from '@clerk/clerk-react';
import axios from 'axios';
import { Activity, RefreshCw, AlertTriangle, CheckCircle, ShieldAlert, Cpu, Download, Pill, Scale, FileText } from 'lucide-react';
import BodyScan3D from '../components/BodyScan3D';
import DiseaseCard from '../components/disease-cards/DiseaseCard';
import { useGoogleLogin } from '@react-oauth/google';
import SavedDoctorsWidget from '../components/dashboard/SavedDoctorsWidget';
import { motion, AnimatePresence } from 'framer-motion';
import { generateDashboardPDF } from '../utils/pdfGenerator';

const API_URL = import.meta.env.VITE_API_URL || 'http://127.0.0.1:5000/api';
// Must match backend HYBRID_DISEASE_IDS order for "Show more" / bootstrap checks.
const FULL_HYBRID_DISEASE_IDS = [
  'diabetes', 'pre_diabetes', 'obesity', 'thyroid', 'pcos', 'hypertension',
  'heart_disease', 'stroke', 'asthma', 'copd', 'ckd', 'fatty_liver',
  'anemia', 'vitamin_d', 'vitamin_b12', 'depression', 'anxiety',
  'sleep_disorders', 'osteoporosis', 'osteoarthritis'
];
const PRIORITY_DISEASES = ['diabetes', 'pre_diabetes', 'hypertension', 'anemia', 'thyroid', 'obesity'];

const Dashboard = () => {
  const { user, isLoaded } = useUser();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [syncing, setSyncing] = useState(false);
  const [error, setError] = useState(null);
  const [feedbackStatus, setFeedbackStatus] = useState({});
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [expandedDiseaseId, setExpandedDiseaseId] = useState(null);
  const [toast, setToast] = useState(null);
  const [latestVitals, setLatestVitals] = useState([]);
  const [medications, setMedications] = useState([]);
  const [profile, setProfile] = useState(null);
  const [showAllRiskCards, setShowAllRiskCards] = useState(false);
  const [scoresAsOf, setScoresAsOf] = useState(null);

  // STEP 62: Global Disease Refresh Mechanism
  const VITAL_IMPACT_MAP = {
    weight: ['diabetes', 'obesity', 'pcos', 'heart_disease', 'fatty_liver', 'hypertension', 'osteoporosis', 'osteoarthritis'],
    waistCircumference: ['diabetes', 'heart_disease', 'hypertension'],
    chestPain: ['heart_disease', 'stroke'],
    shortnessBreath: ['heart_disease', 'asthma', 'copd', 'respiratory'],
    menstrualCycleIrregular: ['pcos'],
    mentalHealthDepressed: ['depression', 'anxiety'],
    mentalHealthAnxiety: ['anxiety', 'depression'],
    abdominalPain: ['fatty_liver', 'ckd', 'surgical'],
    frequentUrination: ['diabetes', 'ckd'],
    dietType: ['diabetes', 'anemia', 'vitamin_b12', 'heart_disease'],
    isSmoker: ['heart_disease', 'stroke', 'asthma', 'copd']
  };

  const needsHybridBootstrap = (scores) => {
    if (!scores || typeof scores !== 'object') return true;
    return FULL_HYBRID_DISEASE_IDS.some((k) => scores[k] === undefined || scores[k] === null);
  };

  /** fullRecompute: run questionnaire hybrid (all diseases) and persist — use after profile edits. */
  const fetchData = async (fullRecompute = true) => {
    if (!user?.id) return;
    try {
      console.log('[Dashboard] fetchData called with fullRecompute:', fullRecompute, 'at', new Date().toISOString());
      let reportData = null;
      try {
        // Add cache-busting timestamp to ensure fresh data
        const r = await axios.get(`${API_URL}/reports/${user.id}?t=${Date.now()}`);
        if (r.data?.status === 'success') {
          reportData = r.data.data;
          console.log('[Dashboard] Report fetched, risk_scores:', Object.keys(reportData.risk_scores || {}).length, 'diseases');
          console.log('[Dashboard] Diabetes score:', reportData.risk_scores?.diabetes);
        }
      } catch (err) {
        if (err.response?.status !== 404) throw err;
      }

      const [vitalsRes, profileRes, medsRes] = await Promise.all([
        axios.get(`${API_URL}/vitals/latest/${user.id}?t=${Date.now()}`).catch(() => null),
        axios.get(`${API_URL}/profile/${user.id}?t=${Date.now()}`).catch(() => null),
        axios.get(`${API_URL}/medications/${user.id}?t=${Date.now()}`).catch(() => null)
      ]);

      if (profileRes?.data?.status === 'success') {
        setProfile(profileRes.data.data);
      }

      const profileOk = profileRes?.data?.status === 'success';
      const needsBootstrap = needsHybridBootstrap(reportData?.risk_scores);
      
      // CRITICAL: Only run hybrid-assessment on initial load or if scores are missing
      // Do NOT run it on every refresh to avoid overwriting manual data updates
      const shouldRunHybrid = profileOk && needsBootstrap;

      if (shouldRunHybrid) {
        console.log('[Dashboard] Running hybrid assessment (bootstrap mode)...');
        try {
          await axios.post(`${API_URL}/reports/hybrid-assessment`, {
            clerkId: user.id,
            persist: true
          });
          const again = await axios.get(`${API_URL}/reports/${user.id}?t=${Date.now()}`);
          if (again.data?.status === 'success') {
            reportData = again.data.data;
            setScoresAsOf(new Date());
            console.log('[Dashboard] ✅ Hybrid assessment complete, updated report');
            console.log('[Dashboard] New diabetes score:', reportData.risk_scores?.diabetes);
          }
        } catch (hybridErr) {
          console.warn('[Dashboard] hybrid-assessment failed:', hybridErr.response?.data || hybridErr.message);
        }
      } else if (fullRecompute && !needsBootstrap) {
        console.log('[Dashboard] Skipping hybrid-assessment (scores exist), just fetching latest report');
      }

      if (reportData) {
        setReport({ ...reportData });
        console.log('[Dashboard] ✅ Report state updated with', Object.keys(reportData.risk_scores || {}).length, 'diseases');
        console.log('[Dashboard] Final diabetes score in state:', reportData.risk_scores?.diabetes);
      } else if (!autoGenerated && !generating) {
        setAutoGenerated(true);
        generateReport();
      }

      if (vitalsRes?.data?.status === 'success') {
        setLatestVitals(vitalsRes.data.data);
      }

      if (medsRes?.data?.status === 'success') {
        setMedications(medsRes.data.data);
      }
    } catch (err) {
      if (err.response?.status !== 404) {
        console.error('Error fetching data:', err);
      }
    } finally {
      setLoading(false);
    }
  };

  const handleDiseaseScoreUpdate = async (diseaseId) => {
    try {
      console.log('[Dashboard] Refreshing scores for disease:', diseaseId);
      setLoading(true);
      await fetchData(true);
      setToast({
        type: 'success',
        message: `${String(diseaseId).replace(/_/g, ' ')} — questionnaire risk scores refreshed.`
      });
      setTimeout(() => setToast(null), 3500);
    } catch (err) {
      console.error('[Dashboard] Failed to refresh dashboard:', err.response?.data || err.message);
      setToast({
        type: 'error',
        message: 'Failed to refresh risk scores. Please try again.'
      });
      setTimeout(() => setToast(null), 3500);
    } finally {
      setLoading(false);
    }
  };

  const handleToggle = async (diseaseId) => {
    const isExpanding = expandedDiseaseId !== diseaseId;
    setExpandedDiseaseId(isExpanding ? diseaseId : null);
    
    if (isExpanding && user?.id) {
      try {
        await axios.post(`${API_URL}/analytics/track`, {
          clerkId: user.id,
          event: 'card_expand',
          diseaseId: diseaseId
        });
        
        await axios.patch(`${API_URL}/profile/card-meta/${user.id}`, {
          updates: { [diseaseId]: { lastExpandedAt: new Date(), expandedCount: (profile?.cardMeta?.[diseaseId]?.expandedCount || 0) + 1 } }
        });
      } catch (err) {
        console.warn('Failed to persist expansion state');
      }
    }
  };

  useEffect(() => {
    if (!isLoaded) return;
    if (!user) {
      setLoading(false);
      return;
    }
    setLoading(true);
    fetchData(true);

    window.refreshDashboard = () => fetchData(true);
    window.onHealthDataUpdate = (diseaseId, undoAction) => {
      const impactedDiseases = VITAL_IMPACT_MAP[diseaseId] || ['overall health'];
      setToast({
        message: `Updated ${impactedDiseases.length > 2 ? 'multiple conditions' : impactedDiseases.join(' & ')}. Recalculating...`,
        type: 'success',
        undoAction: undoAction
      });
      fetchData(true);
      setTimeout(() => setToast(null), 6000);
    };

    window.refreshHealthcareNetwork = () => {
      fetchData(true);
    };

    const onProfileSynced = () => fetchData(true);
    const onVisible = () => {
      if (document.visibilityState === 'visible') fetchData(true);
    };
    window.addEventListener('vaidya-profile-updated', onProfileSynced);
    document.addEventListener('visibilitychange', onVisible);

    const syncInterval = setInterval(() => fetchData(false), 60000);
    return () => {
      clearInterval(syncInterval);
      window.removeEventListener('vaidya-profile-updated', onProfileSynced);
      document.removeEventListener('visibilitychange', onVisible);
      delete window.refreshDashboard;
    };
  }, [user, isLoaded]);

  const generateReport = async () => {
    if (!user?.id) return;
    setGenerating(true);
    setError(null);
    try {
      const res = await axios.post(`${API_URL}/ai/generate-report`, { clerkId: user.id });
      if (res.data.status === 'success') {
        setReport(res.data.data);
      }
    } catch (err) {
      setError("Analysis failed. The AI engine might be busy.");
      console.error(err);
    } finally {
      setGenerating(false);
    }
  };

  const handleExport = async () => {
    try {
      const [profileRes] = await Promise.all([
        axios.get(`${API_URL}/profile/${user.id}`).catch(() => ({ data: { data: null } }))
      ]);
      generateDashboardPDF(
        user.fullName || 'User',
        report,
        profileRes.data?.data,
        medications
      );
    } catch (err) {
      console.error("Export failed:", err);
    }
  };

  if (loading) {
    return <div className="flex min-h-[60vh] items-center justify-center"><RefreshCw className="w-8 h-8 text-emerald-500 animate-spin" /></div>;
  }

  if (!report) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[80vh] text-center max-w-2xl mx-auto animate-fade-in">
         <div className="w-48 h-48 mb-8 opacity-80 flex items-center justify-center bg-gray-50 dark:bg-gray-900/50 rounded-full border-4 border-emerald-500/10 dark:border-emerald-500/20 shadow-[0_0_50px_rgba(16,185,129,0.1)]">
            <Cpu className="w-24 h-24 text-emerald-500 animate-pulse" />
         </div>
         <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">Profile Synchronization Complete</h1>
         <p className="text-gray-600 dark:text-gray-400 mb-8 text-lg">
            Your biometric baseline is ready. Activate the VaidyaSetu AI core to generate your personalized health matrix.
         </p>
         {error && (
           <p className="text-red-400 text-sm mb-4 max-w-md">{error}</p>
         )}
         <button onClick={generateReport} disabled={generating} className="px-8 py-4 bg-emerald-600 hover:bg-emerald-500 text-white rounded-2xl font-bold transition-all disabled:opacity-50 flex items-center shadow-[0_0_20px_rgba(16,185,129,0.3)]">
           {generating ? <><RefreshCw className="w-5 h-5 mr-3 animate-spin" /> Analyzing...</> : <><Activity className="w-5 h-5 mr-3" /> Initiate Predictive Scan</>}
         </button>
         <p className="text-gray-500 text-xs mt-6 max-w-md">
           Tip: after onboarding, risk cards usually fill automatically from your questionnaire. If scores look empty, confirm your profile saved and the API is reachable ({API_URL}).
         </p>
      </div>
    );
  }

  return (
    <div className="animate-in fade-in slide-in-from-bottom-4 duration-700 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12">
      {/* Header Section */}
      <div className="flex flex-col md:flex-row md:items-end justify-between mb-12 gap-6">
        <div>
          <h1 className="text-4xl md:text-5xl font-black text-gray-900 dark:text-white tracking-tighter mb-3">
            Health Ecosystem
          </h1>
          <p className="text-sm font-bold text-gray-400 dark:text-gray-500 uppercase tracking-widest">
            Report from {report?.createdAt ? new Date(report.createdAt).toLocaleDateString('en-GB') : 'N/A'}
            {scoresAsOf && (
              <span className="block text-emerald-600 dark:text-emerald-400 normal-case mt-1 tracking-normal">
                Questionnaire risk scores refreshed {scoresAsOf.toLocaleString()}
              </span>
            )}
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <button
            type="button"
            onClick={() => {
              console.log('[Dashboard] Manual refresh triggered by user');
              setLoading(true);
              fetchData(true).then(() => {
                setToast({
                  type: 'success',
                  message: 'Dashboard refreshed with latest risk scores!'
                });
                setTimeout(() => setToast(null), 3000);
              });
            }}
            className="px-5 py-3 rounded-2xl border border-emerald-500/40 text-emerald-600 dark:text-emerald-400 text-[10px] font-black uppercase tracking-widest hover:bg-emerald-500/10 transition-colors"
          >
            Refresh risk scores
          </button>
          <button onClick={handleExport} className="px-6 py-3 bg-white dark:bg-gray-950 border border-gray-100 dark:border-gray-800 hover:border-emerald-500/50 hover:text-emerald-500 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all flex items-center shadow-xl active:scale-95 text-gray-500 dark:text-gray-400">
             <Download className="w-4 h-4 mr-2" /> Export My Health Data
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Main Column */}
        <div className="lg:col-span-8 space-y-10">
          
          {/* AI Diagnostic Summary Hero (Step 34 Design) */}
          <div className="bg-[#0b0f19] border border-emerald-500/20 p-8 md:p-10 rounded-[3rem] shadow-2xl relative overflow-hidden group">
            <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/5 rounded-full blur-3xl -mr-20 -mt-20 group-hover:bg-emerald-500/10 transition-all duration-700" />
            <div className="relative z-10">
              <h2 className="text-emerald-500 font-black mb-6 flex items-center uppercase tracking-[0.2em] text-[10px]">
                <Cpu className="w-4 h-4 mr-3" /> AI Diagnostic Summary
              </h2>
              <p className="text-gray-300 text-lg md:text-xl leading-relaxed font-medium">
                {report.summary}
              </p>
            </div>
          </div>

          <div className="space-y-6">
            <h3 className="text-gray-900 dark:text-white font-black text-xl tracking-tight">Predictive Risk Vectors</h3>
            <p className="text-xs text-gray-400 font-medium">Click any card to see full analysis, fill missing data for better accuracy, and get personalized mitigations.</p>
            
            {/* Disease Cards Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              {(() => {
                const riskEntries = Object.entries(report?.risk_scores || {});
                const normalizeDiseaseId = (diseaseId = '') => diseaseId.toLowerCase().replace(/[_-\s]/g, '');
                const prioritySet = new Set(PRIORITY_DISEASES.map(normalizeDiseaseId));

                const prioritized = [];
                const remaining = [];

                riskEntries.forEach(([key, score]) => {
                  if (prioritySet.has(normalizeDiseaseId(key))) {
                    prioritized.push([key, score]);
                    return;
                  }
                  remaining.push([key, score]);
                });

                let visibleEntries = showAllRiskCards ? [...prioritized, ...remaining] : prioritized;
                if (!showAllRiskCards && visibleEntries.length === 0 && remaining.length > 0) {
                  visibleEntries = remaining.slice(0, 6);
                }

                if (visibleEntries.length === 0) {
                  return (
                    <div className="md:col-span-2 rounded-[2rem] border border-amber-500/25 bg-amber-500/5 p-8 text-center text-sm text-amber-100">
                      <p className="font-bold text-amber-400 mb-2 uppercase tracking-widest text-[10px]">No risk vectors to show</p>
                      <p className="text-gray-400 mb-4">
                        Your report has no scored conditions yet. Use <strong>Initiate Predictive Scan</strong> (if shown), complete onboarding, or tap Refresh risks below.
                      </p>
                      <button
                        type="button"
                        onClick={async () => {
                          if (!user?.id) return;
                          setLoading(true);
                          try {
                            await axios.post(`${API_URL}/reports/hybrid-assessment`, { clerkId: user.id, persist: true });
                            const r = await axios.get(`${API_URL}/reports/${user.id}`);
                            if (r.data?.status === 'success') setReport(r.data.data);
                          } catch (e) {
                            console.error(e);
                            setToast({ type: 'error', message: 'Could not refresh risks. Check profile and API.' });
                            setTimeout(() => setToast(null), 4000);
                          } finally {
                            setLoading(false);
                          }
                        }}
                        className="px-6 py-3 rounded-xl bg-emerald-600 text-white text-xs font-black uppercase tracking-wider"
                      >
                        Refresh risks from profile
                      </button>
                    </div>
                  );
                }

                return visibleEntries.map(([key, score]) => (
                <DiseaseCard 
                  key={key}
                  diseaseId={key}
                  initialScore={score}
                  clerkId={user.id}
                  profile={profile}
                  isExpanded={expandedDiseaseId === key}
                  onToggle={() => handleToggle(key)}
                  onScoreUpdated={handleDiseaseScoreUpdate}
                />
                ));
              })()}
            </div>
            {(() => {
              const riskEntries = Object.entries(report?.risk_scores || {});
              const normalizeDiseaseId = (diseaseId = '') => diseaseId.toLowerCase().replace(/[_-\s]/g, '');
              const prioritySet = new Set(PRIORITY_DISEASES.map(normalizeDiseaseId));
              const remainingCount = riskEntries.filter(([key]) => !prioritySet.has(normalizeDiseaseId(key))).length;

              if (remainingCount === 0) return null;

              return (
                <button
                  type="button"
                  onClick={() => setShowAllRiskCards(prev => !prev)}
                  className="px-5 py-2 rounded-xl border border-emerald-500/30 text-emerald-600 dark:text-emerald-400 text-xs font-black uppercase tracking-wider hover:bg-emerald-500/10 transition-colors"
                >
                  {showAllRiskCards ? 'Show less' : `Show more (${remainingCount})`}
                </button>
              );
            })()}
          </div>
        </div>

        {/* Sidebar Column */}
        <div className="lg:col-span-4 space-y-8">
            {/* Body Measurements */}
            {profile && (
              <div className="bg-white dark:bg-[#030712] border border-gray-200 dark:border-gray-800/60 rounded-[2.5rem] p-8 shadow-xl space-y-6">
                <h3 className="text-[10px] font-black uppercase tracking-widest text-gray-400 flex items-center gap-2"><Scale className="w-4 h-4 text-emerald-500" /> Body Measurements</h3>
                <div className="grid grid-cols-2 gap-4">
                  <div className="p-4 bg-gray-50 dark:bg-gray-900/50 rounded-2xl text-center">
                    <div className="text-2xl font-black text-gray-900 dark:text-white">{profile.height?.value || '--'}</div>
                    <div className="text-[9px] font-black text-gray-400 uppercase tracking-widest mt-1">Height (cm)</div>
                  </div>
                  <div className="p-4 bg-gray-50 dark:bg-gray-900/50 rounded-2xl text-center">
                    <div className="text-2xl font-black text-gray-900 dark:text-white">{profile.weight?.value || '--'}</div>
                    <div className="text-[9px] font-black text-gray-400 uppercase tracking-widest mt-1">Weight (kg)</div>
                  </div>
                  <div className="p-4 bg-gray-50 dark:bg-gray-900/50 rounded-2xl text-center">
                    <div className={`text-2xl font-black ${profile.bmi?.value >= 25 ? 'text-amber-500' : 'text-emerald-500'}`}>{profile.bmi?.value ? Number(profile.bmi.value).toFixed(1) : '--'}</div>
                    <div className="text-[9px] font-black text-gray-400 uppercase tracking-widest mt-1">BMI</div>
                  </div>
                  <div className="p-4 bg-gray-50 dark:bg-gray-900/50 rounded-2xl text-center">
                    <div className="text-sm font-black text-gray-900 dark:text-white">{profile.bmiCategory?.value || '--'}</div>
                    <div className="text-[9px] font-black text-gray-400 uppercase tracking-widest mt-1">Category</div>
                  </div>
                </div>
              </div>
            )}

            {/* Allergies */}
            {profile?.allergies?.value?.length > 0 && (
              <div className="bg-red-500/5 border border-red-500/10 rounded-[2.5rem] p-6 space-y-4">
                <h3 className="text-[10px] font-black uppercase tracking-widest text-red-400 flex items-center gap-2"><AlertTriangle className="w-4 h-4" /> Declared Allergies</h3>
                <div className="flex flex-wrap gap-2">
                  {profile.allergies.value.map(a => (
                    <span key={a} className="px-3 py-1.5 bg-red-500/10 text-red-400 text-xs font-bold rounded-lg border border-red-500/20">{a}</span>
                  ))}
                </div>
              </div>
            )}

            {/* Active Medicines */}
            {medications.length > 0 && (
              <div className="bg-blue-500/5 border border-blue-500/10 rounded-[2.5rem] p-6 space-y-4">
                <h3 className="text-[10px] font-black uppercase tracking-widest text-blue-400 flex items-center gap-2"><Pill className="w-4 h-4" /> Active Medicines</h3>
                <div className="space-y-2">
                  {medications.slice(0, 5).map(m => (
                    <div key={m._id} className="flex items-center justify-between p-3 bg-white dark:bg-gray-900/50 rounded-xl border border-gray-100 dark:border-gray-800">
                      <span className="text-sm font-bold text-gray-900 dark:text-white">{m.name}</span>
                      <span className="text-[9px] font-bold text-gray-400 uppercase">{m.dosage}</span>
                    </div>
                  ))}
                  {medications.length > 5 && <p className="text-[10px] text-blue-400 font-bold text-center">+{medications.length - 5} more</p>}
                </div>
              </div>
            )}

            {/* 3D Body Scan */}
            <div className="bg-white dark:bg-[#030712] border border-gray-200 dark:border-gray-800/60 rounded-[3rem] min-h-[400px] relative overflow-hidden shadow-2xl">
                <div className="w-full h-[400px]">
                    <BodyScan3D riskScore={Math.max(0, ...Object.values(report?.risk_scores || {}).map(v => Number(v) || 0))} />
                </div>
            </div>

            <SavedDoctorsWidget 
              doctors={profile?.savedDoctors} 
              clerkId={user.id}
              onRefresh={fetchData}
              onRemove={async (placeId) => {
                try {
                  await axios.delete(`${API_URL}/profile/saved-doctors/${user.id}/${placeId}`);
                  fetchData();
                } catch (err) {
                  console.error("Error removing doctor:", err);
                }
              }}
            />

            <div className="bg-red-950/20 border border-red-900/30 p-6 rounded-[2rem] text-center">
               <div className="w-8 h-8 bg-red-500/10 rounded-full flex items-center justify-center mx-auto mb-4">
                  <ShieldAlert className="w-4 h-4 text-red-500" />
               </div>
               <p className="text-red-400/80 text-[10px] font-black uppercase tracking-[0.2em] leading-relaxed">
                  {report?.disclaimer || 'Screening support only — not a medical diagnosis.'}
               </p>
            </div>
        </div>
      </div>

      {/* Persistence Notifications */}
      <div className="fixed bottom-8 left-1/2 -translate-x-1/2 z-[100] w-full max-w-sm px-4 pointer-events-none">
        <AnimatePresence>
          {toast && (
            <motion.div initial={{ opacity: 0, y: 50 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="bg-gray-900 text-white p-5 rounded-[2rem] shadow-2xl flex items-center justify-between pointer-events-auto border border-white/5 backdrop-blur-xl">
              <div className="flex items-center space-x-4">
                <CheckCircle className="w-5 h-5 text-emerald-500" />
                <p className="text-xs font-bold tracking-tight">{toast.message}</p>
              </div>
              {toast.undoAction && (
                <button onClick={() => { toast.undoAction(); setToast(null); }} className="px-4 py-2 bg-white/10 hover:bg-white/20 rounded-xl text-[10px] font-black uppercase tracking-widest transition-colors">Undo</button>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};

export default Dashboard;
